# MySQL. Ensure the MySQL2 gem is defined in your Gemfile
# gem "mysql2"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: debian
  password: ruby1
  host: 127.0.0.1
  port: 3306
  database: RoR

test:
  <<: *default
  username: debian
  password: ruby1
  host: 127.0.0.1
  port: 3306
  database: RoR_test  # Cambia esto a un nombre diferente para la base de datos de prueba

production:
  <<: *default
  # database: path/to/persistent/storage/production.sqlite3

